apiVersion: apps/v1
kind: Deployment
metadata:
  name: czwr-deploy-from-manifest-with-autoscaling
  labels:
    app: my-deploy
    env: prod
    owner: Czwr
spec:
  replicas: 2
  selector:
    matchLabels:
      project: asd
  template:
    metadata:
      labels:
        project: asd
    spec:
      containers:
        - name: asd-web
          image: adv4000/k8sphp:version2
          ports:
            - containerPort: 80           

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: czwr-autospec
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: czwr-deploy-from-manifest-with-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80  